# vim:set ft=tmux:
%hidden MODULE_NAME="sys_ram"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󰍛 "
set -gqF "@catppuccin_${MODULE_NAME}_color" "#81a1c1"
set -gqF "@catppuccin_status_${MODULE_NAME}_icon_fg" "#11111b"
set -gqF "@catppuccin_status_${MODULE_NAME}_text_fg" "#cdd6f4"
set -gqF "@catppuccin_status_${MODULE_NAME}_text_bg" "#45475a"
set -ogq "@catppuccin_${MODULE_NAME}_text" "#(~/dotfiles/tmux/scripts/ram.sh)"

source "~/.tmux/plugins/tmux/utils/status_module.conf"
